### PR TITLE
overlay: base: Update brightness settings

### PR DESCRIPTION
**Pull request by Gray47Maxx**
Took @kholk 's akatsuki commit as an example and tweaked it a bit for the sake of getting even darker screen. Works like a charm on my suzu, so it's merge-ready PR.

### CODE REVIEW

**Comment by stefanhh0** [comment]
It would be better to have this change in a single commit.

**Comment by kholk** [comment]
Please squash the commits.

**Comment by Gray47Maxx** [comment]
Will do in a couple of hours, sry for the mess

**Comment by kholk** [comment]
No problem, take your time

**Comment by Gray47Maxx** [comment]
#2 sorry for that mess. Let me close and clean my branch, then I'll do a proper PR.

**Comment by MarijnS95** [comment]
@Gray47Maxx No need to close this and create *yet another* PR. Just force-push to this branch and it'll all clean itself up nicely.
(Except that github nowadays shows force-pushes, but only the commit history matters)

**Comment by Gray47Maxx** [comment]
Sorry, can't reopen it already because I've messed so much that I've deleted the whole repo :/

Git is, without doubt, not my strong point, but next time I'll be way more serious with that things.

**Comment by MarijnS95** [comment]
Don't worry, we're all here to learn new things. Be it git, code or otherwise.

Reopening PR's has always been an issue. I've never gotten it to work, but after a quick search it turns out that the branch needs to point to the same commit when it was closed. New changes should be force-pushed only after reopening. Alin should have the power to do so.

**Pull request closed without merging**
