### PR TITLE
config: Update brightness settings

### PR DESCRIPTION
**Pull request by Gray47Maxx**
Took @kholk 's akatsuki commit as an example and tweaked it a bit for the sake of getting even darker screen. Works like a charm on my suzu, so it's merge-ready PR.

This time in one commit and without errors and mess in general.

### CODE REVIEW

**Comment by kholk** [comment]
Oki, now that the commit is properly formatted I can give my blessing.

**Comment by bartcubbins** [comment]
what about kugo?

**Comment by kholk** [comment]
This should be ported on all devices really.
It's a consequence of my changes in the lights hal...

**Comment by Gray47Maxx** [comment]
I'll do it for all devices asap, but I'd need some people to test the changes

**Pull request merged**
